### ISSUE TITLE
Support for MS Edge

### ISSUE THREAD

**Issue by usopp-airmash** [airmash-refugees/airmash-frontend#13]
JOS was logged out of the game after pressing enter twice. He was using Edge at that time.

**Comment by congratulatio** [comment]
Do you have further details? I can't reproduce this.

**Comment by usopp-airmash** [comment]
I have only a video message from JOS. From what I could see he used Edge when encountering the problem. I don't know if I should post the video here :D.

**Comment by congratulatio** [comment]
If JOS is okay with his gameplay video being shared, please send to airmashonline@gmail.com and I will take a look. Thanks!

**Comment by usopp-airmash** [comment]
I've sent you the detailed videos.

**Comment by congratulatio** [comment]
Thanks, with the help of JOS's videos, I understand the repro steps while playing are:

1. Press Enter (chat input opens)
2. Type anything
3. Press Enter (chat input closes)
4. Press Enter (refreshes page)

I think I have a fix, just testing it now. Looks like the problem is some `<form>` tags that wrap the chat input, introduced while refactoring the original airma.sh code.

**Comment by congratulatio** [comment]
The fix looks like it worked, and it's now deployed onto https://airmash.online. Please reopen the issue if there are still problems.
