### ISSUE TITLE
Missing missiles

### ISSUE THREAD

**Issue by usopp-airmash** [airmash-refugees/airmash-frontend#20]
Somehow the missiles are not displayed
![Screenshot from 2019-12-07 22-26-35](https://user-images.githubusercontent.com/49999219/70380811-2c003080-1941-11ea-98d4-0cac5706d585.png)
Germany base is also missing
![Screenshot from 2019-12-07 22-36-23](https://user-images.githubusercontent.com/49999219/70380872-3242dc80-1942-11ea-8ce5-d1f37b966d4f.png)

**Comment by congratulatio** [comment]
Could you try https://old.airmash.online and https://test.airmash.online to see if the same happens on either of these?

Is this occurring with every missile and base?

What OS and browser are you using?

Earlier today I synced https://airmash.online with this repo, when previously it was on https://github.com/airmash-refugees/airmash-frontend/commit/deb6afe878c3b83604d092d37c864f3c44d11ff1 (from 7th Nov), I guess it must be one of the changes since then.

**Comment by congratulatio** [comment]
I think I see what happened. Earlier today, I synced https://airmash.online with the latest commit (https://github.com/airmash-refugees/airmash-frontend/commit/367740fd9f16cc6320bcc20c8d604f64488d9061). Previously it was on https://github.com/airmash-refugees/airmash-frontend/commit/deb6afe878c3b83604d092d37c864f3c44d11ff1, from 7th Nov.

Since that date, [items.png](https://github.com/airmash-refugees/airmash-frontend/blob/master/src/assets/items.png), which contains the graphics for both missiles and bases, has been [updated](https://github.com/airmash-refugees/airmash-frontend/commits/master/src/assets/items.png), but the reference to it in [Textures.js](https://github.com/airmash-refugees/airmash-frontend/blob/master/src/js/Textures.js) has not:

https://github.com/airmash-refugees/airmash-frontend/blob/367740fd9f16cc6320bcc20c8d604f64488d9061/src/js/Textures.js#L14

When https://airmash.online/assets/items.png?2 was requested, your browser must have served up the cached copy, which is too small for some of the new textures and gives the following error when loading:

```
Uncaught Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 4 + 128 = 132 > 1024 or Y: 409 + 128 = 537 > 512
    at t.set (Texture.js:578)
    at t.onBaseTextureLoaded (Texture.js:220)
    at t.a.emit (index.js:150)
    at Image.e.onload (BaseTexture.js:386)
```

**Comment by congratulatio** [comment]
I've updated https://airmash.online with the fix (https://github.com/airmash-refugees/airmash-frontend/commit/cd75a40cc94b95fb0e36a19f1e6a9f56cf174d94) for this, it should sort itself out if you refresh/reload the site in your browser.

Please reopen the issue if there are still problems. Thanks!
