### ISSUE TITLE
Websocket connection failed

### ISSUE THREAD

**Issue by usopp-airmash** [airmash-refugees/airmash-frontend#21]
Kids from US are complaining that they got banned because of that message. Could you have a look at the details? I have told them to post screenshots on reddit. Not sure if they would listen to me.

**Comment by congratulatio** [comment]
Thanks for reporting this! If they see that message, it means they can't connect to the server at all for some reason.

If the admins/mods of a server have banned them, this should mean they connect, get an error packet sent back to the client, and are then disconnected. This causes a different error message to appear, indicating a ban.

It's most likely to be one of these conditions causing the websocket connection error:
1. Their connections to the game server are being blocked because of some condition on their local network
2. The game server they were connecting to was temporarily unavailable
3. The game server operator has implemented an IP ban that doesn't send an error message, and instead breaks or blocks the connection (though I'm not aware of anyone doing this)

**Comment by congratulatio** [comment]
Following some related discussion on reddit, I've made some changes to the error messages when a player is banned (https://github.com/airmash-refugees/airmash-frontend/commit/c602dca65b80816eebeb09e5f25a291f251a5f91) to help clarify exactly which server they are banned from.
